In [2]:
with open(RAW_FILE, "r") as f:
    for _ in range(5):
        print(f.readline())

C,SETP.WORLD,DVD_DISPATCHPRICE,AEMO,PUBLIC,2025/08/08,09:36:13,001754609773098,MONTHLY_ARCHIVE,001754609773098

I,DISPATCH,PRICE,5,SETTLEMENTDATE,RUNNO,REGIONID,DISPATCHINTERVAL,INTERVENTION,RRP,EEP,ROP,APCFLAG,MARKETSUSPENDEDFLAG,LASTCHANGED,RAISE6SECRRP,RAISE6SECROP,RAISE6SECAPCFLAG,RAISE60SECRRP,RAISE60SECROP,RAISE60SECAPCFLAG,RAISE5MINRRP,RAISE5MINROP,RAISE5MINAPCFLAG,RAISEREGRRP,RAISEREGROP,RAISEREGAPCFLAG,LOWER6SECRRP,LOWER6SECROP,LOWER6SECAPCFLAG,LOWER60SECRRP,LOWER60SECROP,LOWER60SECAPCFLAG,LOWER5MINRRP,LOWER5MINROP,LOWER5MINAPCFLAG,LOWERREGRRP,LOWERREGROP,LOWERREGAPCFLAG,PRICE_STATUS,PRE_AP_ENERGY_PRICE,PRE_AP_RAISE6_PRICE,PRE_AP_RAISE60_PRICE,PRE_AP_RAISE5MIN_PRICE,PRE_AP_RAISEREG_PRICE,PRE_AP_LOWER6_PRICE,PRE_AP_LOWER60_PRICE,PRE_AP_LOWER5MIN_PRICE,PRE_AP_LOWERREG_PRICE,CUMUL_PRE_AP_ENERGY_PRICE,CUMUL_PRE_AP_RAISE6_PRICE,CUMUL_PRE_AP_RAISE60_PRICE,CUMUL_PRE_AP_RAISE5MIN_PRICE,CUMUL_PRE_AP_RAISEREG_PRICE,CUMUL_PRE_AP_LOWER6_PRICE,CUMUL_PRE_AP_LOWER60_PRICE,CUMUL_PRE_AP_LOWER5MIN_PRICE,CUMUL_PRE_AP_LOWERREG_PRICE,OCD_STATUS,MII_STATUS,RAISE1SECRRP,RAISE1SECROP,RAISE1SECAPCFLAG,LOWER1SECRRP,LOWER1SECROP,LOWER1SECAPCFLAG,PRE_AP_RAISE1_PRICE,PRE_AP_LOWER1_PRICE,CUMUL_PRE_AP_RAISE1_PRICE,CUMUL_PRE_AP_LOWER1_PRICE

D,DISPATCH,PRICE,5,"2025/07/01 00:05:00",1,NSW1,20250630241,0,176.71,0,176.71,0,0,"2025/07/01 00:00:03",0.38,0.38,0,0.38,0.38,0,0.32,0.32,0,4.99,4.99,0,0.1,0.1,0,0.38,0.38,0,0.1,0.1,0,3.99,3.99,0,FIRM,176.71,0.38,0.38,0.32,4.99,0.1,0.38,0.1,3.99,852612.65903,5633.82397,3114.20499,390.48803,17457.75648,490.13359,1032.75162,468.75231,4664.36198,NOT_OCD,NOT_MII,0.86,0.86,0,0,0,0,0.86,0,796.5661,3.78

D,DISPATCH,PRICE,5,"2025/07/01 00:05:00",1,QLD1,20250630241,0,153.51486,0,153.51486,0,0,"2025/07/01 00:00:03",0.38,0.38,0,0.38,0.38,0,0.32,0.32,0,4.99,4.99,0,0.1,0.1,0,0.38,0.38,0,0.1,0.1,0,3.99,3.99,0,FIRM,153.51486,0.38,0.38,0.32,4.99,0.1,0.38,0.1,3.99,282861.87471,5633.82397,3114.20499,390.48803,17457.75648,490.13359,1032.75162,468.75231,4664.36198,NOT_OCD,NOT_MII,0.86,0.86,0,0,0,0,0.86,0,796.5661,3.78

D,DISPATCH,PRICE,5,"2025/07/01 00:05:00",1,SA1,20250630241,0,172.48363,0,172.48363,0,0,"2025/07/01 00:00:03",0.38,0.38,0,0.38,0.38,0,0.32,0.32,0,4.99,4.99,0,0.39,0.39,0,0.39,0.39,0,0.1,0.1,0,3.99,3.99,0,FIRM,172.48363,0.38,0.38,0.32,4.99,0.39,0.39,0.1,3.99,843055.15655,5633.86397,3115.47499,390.49803,17457.76648,2600.06522,3132.2784,521.0409,4716.65057,NOT_OCD,NOT_MII,0.86,0.86,0,0,0,0,0.86,0,796.5661,2848.69

In [3]:
import csv
import pandas as pd

rows = []

with open(RAW_FILE, "r", newline="") as f:
    reader = csv.reader(f)

    for row in reader:
        if row[0] == "I" and row[1] == "DISPATCH" and row[2] == "PRICE":
            columns = row[4:]

        elif row[0] == "D" and row[1] == "DISPATCH" and row[2] == "PRICE":
            rows.append(row[4:])

In [4]:
df = pd.DataFrame(rows, columns=columns)

df.head()

,SETTLEMENTDATE,RUNNO,REGIONID,DISPATCHINTERVAL,INTERVENTION,RRP,EEP,ROP,APCFLAG,MARKETSUSPENDEDFLAG,...,RAISE1SECRRP,RAISE1SECROP,RAISE1SECAPCFLAG,LOWER1SECRRP,LOWER1SECROP,LOWER1SECAPCFLAG,PRE_AP_RAISE1_PRICE,PRE_AP_LOWER1_PRICE,CUMUL_PRE_AP_RAISE1_PRICE,CUMUL_PRE_AP_LOWER1_PRICE
0,2025/07/01 00:05:00,1,NSW1,20250630241,0,176.71,0,176.71,0,0,...,0.86,0.86,0,0,0,0,0.86,0,796.5661,3.78
1,2025/07/01 00:05:00,1,QLD1,20250630241,0,153.51486,0,153.51486,0,0,...,0.86,0.86,0,0,0,0,0.86,0,796.5661,3.78
2,2025/07/01 00:05:00,1,SA1,20250630241,0,172.48363,0,172.48363,0,0,...,0.86,0.86,0,0,0,0,0.86,0,796.5661,2848.69
3,2025/07/01 00:05:00,1,TAS1,20250630241,0,155.64667,0,155.64667,0,0,...,0.86,0.86,0,0,0,0,0.86,0,704.65393,2.25
4,2025/07/01 00:05:00,1,VIC1,20250630241,0,176.61966,0,176.61966,0,0,...,0.86,0.86,0,0,0,0,0.86,0,796.5661,3.78

In [5]:
df = df[["SETTLEMENTDATE", "REGIONID", "RRP"]]

df.head()

        SETTLEMENTDATE REGIONID        RRP
0  2025/07/01 00:05:00     NSW1     176.71
1  2025/07/01 00:05:00     QLD1  153.51486
2  2025/07/01 00:05:00      SA1  172.48363
3  2025/07/01 00:05:00     TAS1  155.64667
4  2025/07/01 00:05:00     VIC1  176.61966

In [6]:
df_vic = df[df["REGIONID"] == "VIC1"].copy()

df_vic.head()

         SETTLEMENTDATE REGIONID        RRP
4   2025/07/01 00:05:00     VIC1  176.61966
9   2025/07/01 00:10:00     VIC1  182.30989
14  2025/07/01 00:15:00     VIC1   169.4761
19  2025/07/01 00:20:00     VIC1  184.67607
24  2025/07/01 00:25:00     VIC1    185.739

In [7]:
df_vic["SETTLEMENTDATE"] = pd.to_datetime(df_vic["SETTLEMENTDATE"])
df_vic["RRP"] = pd.to_numeric(df_vic["RRP"])

df_vic.info()

<class 'pandas.DataFrame'>
Index: 8928 entries, 4 to 44636
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   SETTLEMENTDATE  8928 non-null   datetime64[us]
 1   REGIONID        8928 non-null   str
 2   RRP             8928 non-null   float64
dtypes: datetime64[us](1), float64(1), str(1)
memory usage: 279.0 KB

In [8]:
df_vic

           SETTLEMENTDATE REGIONID        RRP
4     2025-07-01 00:05:00     VIC1  176.61966
9     2025-07-01 00:10:00     VIC1  182.30989
14    2025-07-01 00:15:00     VIC1  169.47610
19    2025-07-01 00:20:00     VIC1  184.67607
24    2025-07-01 00:25:00     VIC1  185.73900
...                   ...      ...        ...
44619 2025-07-31 23:40:00     VIC1  161.67743
44624 2025-07-31 23:45:00     VIC1  158.00000
44629 2025-07-31 23:50:00     VIC1  165.95947
44634 2025-07-31 23:55:00     VIC1  135.54016
44636 2025-08-01 00:00:00     VIC1  137.28722

[8928 rows x 3 columns]

In [9]:
df_vic.shape

(8928, 3)

In [10]:
df_vic["SETTLEMENTDATE"].duplicated().sum()

np.int64(0)

In [11]:
df_vic.isna().sum()

SETTLEMENTDATE    0
REGIONID          0
RRP               0
dtype: int64

In [12]:
time_diff = df_vic["SETTLEMENTDATE"].sort_values().diff()

time_diff.value_counts().head()

SETTLEMENTDATE
0 days 00:05:00    8927
Name: count, dtype: int64

In [13]:
df_vic["RRP"].describe()

count    8928.000000
mean       82.133344
std        81.336518
min      -468.931360
25%         8.950000
50%        69.904240
75%       135.442580
max       406.480000
Name: RRP, dtype: float64

In [14]:
df_vic["RRP"].min(), df_vic["RRP"].max()

(np.float64(-468.93136), np.float64(406.48))

In [16]:
negative_intervals = (df_vic["RRP"] < 0).sum()
negative_pct = negative_intervals / len(df_vic) * 100

print(f"Negative price intervals: {negative_intervals}")
print(f"Percentage: {negative_pct:.2f}%")

Negative price intervals: 1102
Percentage: 12.34%